### PR TITLE
EX-3449 Update Sovrn doc to show video support

### PR DESCRIPTION
**Pull request by mikhalovich**

### CODE REVIEW

**Comment by mikhalovich** [comment]
Adapters that contains video media type are selected [here](https://github.com/sovrn/prebid.github.io/blob/master/formats/video.md?plain=1#L39)

**Review by jrosendahl — APPROVED** [review]
Need to wait for adapter pr to be ready

**Comment by egsgordeev** [comment]
@mikhalovich 
cc: @jrosendahl 

Would it be more appropriate to also add all the video/banner expected params [like other bidders do](https://docs.prebid.org/dev-docs/bidders/beachfront.html)?

**Comment by egsgordeev** [comment]
Review along with https://github.com/sovrn/prebid.github.io/pull/1

**Review by cpabst — APPROVED** [review]
LGTM

**Comment by cpabst** [comment]
Closing this PR in favor of EX-3550

**Pull request closed without merging**
